### ISSUE TITLE
"Select Cities" first load page - Language on "Select City" title is Spanish

### ISSUE THREAD

**Issue by fpuebla** [belatrix/BelatrixEventsAndroid#10]
Steps:

Set up English Language into mobile
Enter to the app (first time)
Verify Language on "Select City" title

Expected:

Language "Select City" title should be English on "Select Cities" first load page

Actual:

"Select Cities" first load page - Language on "Select City" title is Spanish: "Elije tu ciudad"

![2017-04-21_1555](https://cloud.githubusercontent.com/assets/27304405/25292094/1c7aa70c-26ab-11e7-8ab8-d42d1b2185ee.png)

**Comment by carlosmonzon** [comment]
@neosergio @diegoveloper  
We don't have  **"Elije tu ciudad"** string in resources but we do have the following strings key:

```
<string name="label_settings_select_city">Select a City</string>
<string name="label_settings_select_city">Seleccione una ciudad</string>
```
I suggest to use those instead

**Comment by carlosmonzon** [comment]
bug fixed in development

**Comment by fpuebla** [comment]
verified fix in Dev
