### ISSUE TITLE
Prevent to add more than one event to the calendar (Event first time to load)

### ISSUE THREAD

**Issue by fpuebla** [belatrix/BelatrixEventsAndroid#5]
Steps:

1. Enter to the app
2. Tap on any Event
3. Register to the Event
4. Tap on Back
5. Enter again to the same Event
6. Tap on Register

Expected:

- Prevent to add more than one event to the calendar (Event first time to load)

Actual:

- Prevent to add more than one event to the calendar

**Comment by carlosmonzon** [comment]
bug fixed in development

**Comment by fpuebla** [comment]
verified fix in Dev
