### ISSUE TITLE
Add a warning message when the connection is lost

### ISSUE THREAD

**Issue by fpuebla** [belatrix/BelatrixEventsAndroid#7]
When the connection is lost there is no warning message in order to prevent to the user. The system should display a warning message when the connection is lost.

![screenshot_20170419-153152](https://cloud.githubusercontent.com/assets/27304405/25196412/f89120c2-2516-11e7-8e57-3a77816a9d1d.png)

**Comment by carlosmonzon** [comment]
internet lost connection message added

**Comment by fpuebla** [comment]
Verified changes in Dev
